<?php
if (session_status() === PHP_SESSION_NONE) session_start();
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../core/_activity_viewer_template.php';

$activityId = isset($_GET['id']) ? trim((string)$_GET['id']) : '';
$unit = isset($_GET['unit']) ? trim((string)$_GET['unit']) : '';
$returnTo = isset($_GET['return_to']) ? trim((string)$_GET['return_to']) : '';
$isStaff = !empty($_SESSION['academic_logged']) || !empty($_SESSION['admin_logged']);
if ($activityId === '' && $unit === '') die('Activity not specified');

function mzk_default_title(): string { return 'Vocabulary Maze'; }
function mzk_clean_positions($raw): array {
    $out = [];
    if (is_string($raw)) { $d = json_decode($raw, true); $raw = is_array($d) ? $d : []; }
    if (!is_array($raw)) return $out;
    foreach ($raw as $key => $p) {
        if (!preg_match('/^(path|branch)_\d+$/', (string)$key) || !is_array($p)) continue;
        $x = isset($p['x']) ? (float)$p['x'] : null;
        $y = isset($p['y']) ? (float)$p['y'] : null;
        if ($x === null || $y === null || !is_finite($x) || !is_finite($y)) continue;
        $out[(string)$key] = ['x' => $x, 'y' => $y];
    }
    return $out;
}
function mzk_normalize_payload($raw): array {
    $default = ['title'=>mzk_default_title(),'theme'=>'','difficulty'=>'medium','vocabulary_bank'=>[],'path_sequence'=>[],'distractor_branches'=>[],'layout_positions'=>[],'audio_urls'=>[]];
    if ($raw === null || $raw === '') return $default;
    $d = is_string($raw) ? json_decode($raw, true) : $raw;
    if (!is_array($d)) return $default;
    $bank = [];
    foreach (($d['vocabulary_bank'] ?? []) as $item) {
        if (!is_array($item)) continue;
        $word = trim((string)($item['word'] ?? ''));
        $img = trim((string)($item['image_url'] ?? ''));
        if ($word === '' && $img === '') continue;
        $bank[] = ['id'=>trim((string)($item['id'] ?? uniqid('mzk_'))) ?: uniqid('mzk_'),'image_url'=>$img,'word'=>$word];
    }
    $bankIds = array_column($bank, 'id');
    $path = [];
    foreach (($d['path_sequence'] ?? []) as $vid) { $vid = trim((string)$vid); if ($vid !== '' && in_array($vid, $bankIds, true)) $path[] = $vid; }
    if (!$path && $bankIds) $path = $bankIds;
    $branches = [];
    foreach (($d['distractor_branches'] ?? []) as $br) {
        if (!is_array($br)) continue;
        $vid = trim((string)($br['vocabulary_id'] ?? ''));
        if ($vid === '' || !in_array($vid, $bankIds, true)) continue;
        $after = max(0, min(max(0, count($path)-1), (int)($br['attach_after_index'] ?? 0)));
        $branches[] = ['attach_after_index'=>$after,'vocabulary_id'=>$vid];
    }
    $audio = [];
    if (is_array($d['audio_urls'] ?? null)) foreach ($d['audio_urls'] as $vid => $url) { $vid=trim((string)$vid); $url=trim((string)$url); if ($vid!=='' && $url!=='') $audio[$vid]=$url; }
    $difficulty = trim((string)($d['difficulty'] ?? 'medium'));
    if (!in_array($difficulty, ['easy','medium','hard'], true)) $difficulty = 'medium';
    return ['title'=>trim((string)($d['title'] ?? '')) ?: mzk_default_title(),'theme'=>trim((string)($d['theme'] ?? '')),'difficulty'=>$difficulty,'vocabulary_bank'=>$bank,'path_sequence'=>$path,'distractor_branches'=>$branches,'layout_positions'=>mzk_clean_positions($d['layout_positions'] ?? []),'audio_urls'=>$audio];
}
function mzk_resolve_unit(PDO $pdo, string $activityId): string { if ($activityId==='') return ''; $s=$pdo->prepare('SELECT unit_id FROM activities WHERE id=:id LIMIT 1'); $s->execute(['id'=>$activityId]); $r=$s->fetch(PDO::FETCH_ASSOC); return $r && isset($r['unit_id']) ? (string)$r['unit_id'] : ''; }
function mzk_load(PDO $pdo, string $activityId, string $unit): array {
    $fallback = array_merge(['id'=>''], mzk_normalize_payload(null));
    $row = null;
    if ($activityId !== '') { $s=$pdo->prepare("SELECT id,data FROM activities WHERE id=:id AND type='maze_kids' LIMIT 1"); $s->execute(['id'=>$activityId]); $row=$s->fetch(PDO::FETCH_ASSOC); }
    if (!$row && $unit !== '') { $s=$pdo->prepare("SELECT id,data FROM activities WHERE unit_id=:unit AND type='maze_kids' ORDER BY id ASC LIMIT 1"); $s->execute(['unit'=>$unit]); $row=$s->fetch(PDO::FETCH_ASSOC); }
    if (!$row) return $fallback;
    return array_merge(['id'=>(string)($row['id'] ?? '')], mzk_normalize_payload($row['data'] ?? null));
}
if ($unit === '' && $activityId !== '') $unit = mzk_resolve_unit($pdo, $activityId);
$activity = mzk_load($pdo, $activityId, $unit);
$viewerTitle = $activity['title'];
if ($activityId === '' && !empty($activity['id'])) $activityId = $activity['id'];
if (count($activity['path_sequence']) === 0) {
    ob_start(); ?><div style="padding:40px;text-align:center;font-family:Nunito,Arial,sans-serif"><h2><?php echo htmlspecialchars($viewerTitle, ENT_QUOTES, 'UTF-8'); ?></h2><p>This maze needs a path sequence before students can play.</p><?php if ($isStaff): ?><a href="editor.php?unit=<?php echo urlencode($unit); ?><?php echo $activityId!==''?'&id='.urlencode($activityId):''; ?>">Configure maze</a><?php endif; ?></div><?php
    $content = ob_get_clean(); render_activity_viewer($viewerTitle, 'Maze', $content); exit;
}
$bankById = [];
foreach ($activity['vocabulary_bank'] as $item) $bankById[$item['id']] = $item;
ob_start();
?>
<link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@500;600;700&family=Nunito:wght@600;700;800;900&display=swap" rel="stylesheet">
<style>
:root{--mz-orange:#F97316;--mz-purple:#7F77DD;--mz-purple-dark:#534AB7;--mz-purple-soft:#EEEDFE;--mz-muted:#9B94BE;--mz-green:#16a34a;--mz-green-soft:#f0fdf4;--mz-green-dark:#15803d;--mz-red:#ef4444;--mz-red-soft:#fef2f2;--mz-red-light:#FCA5A5;--wall:#CDC7F3}
html,body{width:100%;min-height:100%}
body{margin:0!important;padding:0!important;background:#F8F7FF!important;font-family:'Nunito','Segoe UI',sans-serif!important;overflow-x:hidden}
.activity-wrapper{max-width:100%!important;margin:0!important;padding:0!important;background:transparent!important}.top-row,.activity-header,.activity-title,.activity-subtitle{display:none!important}.viewer-content{padding:0!important;margin:0!important;background:transparent!important;border:none!important;box-shadow:none!important;border-radius:0!important;overflow:visible!important}
.mzk-page{width:100%;height:calc(100vh - 44px);min-height:calc(100vh - 44px);padding:6px 10px 8px;display:flex;align-items:stretch;justify-content:center;background:#F8F7FF;box-sizing:border-box}.mzk-app{width:min(1560px,100%);min-height:0;display:flex;flex-direction:column;gap:8px;margin:0 auto}.mzk-topbar{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:34px}.mzk-title-block{display:flex;align-items:center;gap:10px;min-width:0}.mzk-kicker{display:inline-flex;padding:5px 12px;border-radius:999px;background:#FFF0E6;border:1px solid #FCDDBF;color:#C2580A;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;white-space:nowrap}.mzk-title{font-family:'Fredoka',sans-serif;font-size:clamp(18px,2vw,28px);color:var(--mz-orange);margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mzk-scorebar{display:flex;align-items:center;gap:10px;min-width:min(480px,44vw)}.mzk-score-label{font-size:12px;font-weight:900;color:var(--mz-purple-dark);white-space:nowrap}.mzk-track{flex:1;height:10px;background:var(--mz-purple-soft);border-radius:999px;overflow:hidden}.mzk-fill{height:100%;background:linear-gradient(90deg,var(--mz-orange),var(--mz-purple));border-radius:999px;transition:width .25s}.mzk-badge{min-width:86px;text-align:center;padding:6px 10px;border-radius:999px;background:var(--mz-purple);color:#fff;font-size:12px;font-weight:900;white-space:nowrap}
.mzk-stage{flex:1;min-height:0;background:#fff;border:1px solid #F0EEF8;border-radius:26px;padding:14px 16px 10px;box-shadow:0 8px 40px rgba(127,119,221,.13);width:100%;box-sizing:border-box;display:flex;flex-direction:column;overflow:hidden}.mzk-play-area{flex:1;min-height:0;display:grid;grid-template-columns:minmax(0,1fr) minmax(150px,210px);gap:clamp(14px,2.4vw,24px);align-items:start}.mzk-maze-wrap{min-width:0;min-height:0;display:flex;align-items:center;justify-content:center;overflow:hidden;padding:0}.mzk-maze-wrap svg{display:block;width:100%;height:auto;max-width:100%;max-height:calc(100vh - 186px);object-fit:contain}
.mzk-side-rail{width:100%;display:flex;flex-direction:column;align-items:stretch;justify-content:flex-start;gap:12px}.mzk-controls{width:100%;display:flex;flex-direction:column;gap:8px;padding:10px;border-radius:22px;background:#fff;border:1px solid #EDE9FA;box-shadow:0 8px 24px rgba(127,119,221,.08);text-align:center;box-sizing:border-box}.mzk-btn{width:100%;padding:12px 14px;border:none;border-radius:12px;background:var(--mz-purple);color:#fff;cursor:pointer;font-weight:900;font-family:'Nunito',sans-serif;font-size:13px;box-shadow:0 6px 18px rgba(127,119,221,.18)}.mzk-btn.secondary{background:#F97316}.mzk-btn.next{background:#7F77DD}.mzk-side-hint{color:#8B83C8;font-size:12px;font-weight:900;line-height:1.18;text-align:center;padding:0 8px}.mzk-node{cursor:pointer}.mzk-node-circle{fill:#fff;stroke:none}.mzk-node.done .mzk-node-circle{stroke:var(--mz-green);stroke-width:4;fill:var(--mz-green-soft)}.mzk-node.wrong .mzk-node-circle{stroke:var(--mz-red);stroke-width:4;fill:var(--mz-red-soft)}.mzk-node image{pointer-events:none}.mzk-node.shake{animation:mzkShake .4s}@keyframes mzkShake{10%,90%{transform:translateX(-2px)}20%,80%{transform:translateX(3px)}30%,50%,70%{transform:translateX(-5px)}40%,60%{transform:translateX(5px)}}
#mzkFeedback{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}.mzk-completed-screen{display:none}.mzk-completed-screen.active{display:flex;align-items:center;justify-content:center;position:absolute;inset:0;background:rgba(255,255,255,.82);z-index:40;padding:16px}.mzk-stage.is-completed .mzk-play-area,.mzk-stage.is-completed>.mzk-controls{display:none}.mzk-answer-path{fill:none;stroke:#F97316;stroke-width:12;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:18 12;filter:drop-shadow(0 3px 5px rgba(249,115,22,.35));pointer-events:none}.mzk-answer-dot{fill:#F97316;stroke:#fff;stroke-width:4;pointer-events:none}
.af-unscored__card{background:#fff;border:1.5px solid #EDE9FA;border-radius:14px;padding:28px 32px;width:100%;max-width:520px;box-sizing:border-box;font-family:'Nunito','Segoe UI',sans-serif}.af-unscored__prog-label{font-size:11px;color:#9B8FCC;font-weight:700;letter-spacing:.06em;text-align:center;margin-bottom:6px;text-transform:uppercase}.af-unscored__prog-track{background:#EDE9FA;border-radius:99px;height:9px;overflow:hidden;margin-bottom:4px}.af-unscored__prog-fill{height:100%;border-radius:99px;background:linear-gradient(90deg,#F97316,#7F77DD);transition:width .4s ease}.af-unscored__prog-nums{display:flex;justify-content:space-between;font-size:11px;color:#9B8FCC;margin-bottom:16px}.af-unscored__prog-nums strong{color:#7F77DD}.af-unscored__icon{width:48px;height:48px;border-radius:50%;background:#EDE9FA;display:flex;align-items:center;justify-content:center;margin:0 auto 10px}.af-unscored__title{font-family:'Fredoka','Trebuchet MS',sans-serif;font-size:20px;font-weight:600;color:#7F77DD;text-align:center;margin:0 0 3px}.af-unscored__sub{font-size:13px;color:#9B8FCC;font-weight:600;text-align:center;margin:0 0 16px}.af-unscored__chips{display:grid;gap:8px;margin-bottom:16px}.af-unscored__chips--2{grid-template-columns:1fr 1fr}.af-unscored__chip{background:#F9F8FF;border:1.5px solid #EDE9FA;border-radius:12px;padding:10px 6px;text-align:center}.af-unscored__chip-val{font-family:'Fredoka','Trebuchet MS',sans-serif;font-size:24px;color:#7F77DD;line-height:1}.af-unscored__chip-val--orange{color:#F97316}.af-unscored__chip-lbl{font-size:10px;color:#9B8FCC;font-weight:700;letter-spacing:.05em;margin-top:2px;text-transform:uppercase}.af-unscored__banner{border-radius:12px;padding:9px 14px;display:flex;align-items:center;gap:10px;margin-bottom:16px}.af-unscored__banner--orange{background:#FFF0E6}.af-unscored__banner-icon{width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0}.af-unscored__banner-icon--orange{background:#F97316}.af-unscored__banner-text{font-size:12px;font-weight:600}.af-unscored__banner-text--orange{color:#b85a10}.af-unscored__banner-title{font-family:'Fredoka','Trebuchet MS',sans-serif;font-size:15px;display:block}.af-unscored__btns{display:flex;gap:8px}.af-unscored__btn-primary{flex:1;background:#F97316;color:#fff;border:none;border-radius:10px;padding:11px 0;font-family:'Nunito','Segoe UI',sans-serif;font-size:14px;font-weight:700;cursor:pointer}.af-unscored__btn-secondary{flex:1;background:#fff;color:#7F77DD;border:1.5px solid #EDE9FA;border-radius:10px;padding:11px 0;font-family:'Nunito','Segoe UI',sans-serif;font-size:14px;font-weight:700;cursor:pointer}
@media(max-width:980px){.mzk-app{width:min(100%,1360px)}.mzk-play-area{gap:10px}.mzk-maze-wrap svg{max-height:calc(100vh - 202px)}}@media(max-width:760px){.mzk-page{padding:6px}.mzk-topbar{align-items:stretch;flex-direction:column}.mzk-scorebar{min-width:0;width:100%}.mzk-stage{border-radius:20px;padding:8px}.mzk-play-area{grid-template-columns:1fr;gap:14px}.mzk-side-rail{order:-1;display:grid;grid-template-columns:1fr 1fr;align-items:start}.mzk-side-hint{grid-column:1/-1}.mzk-maze-wrap svg{max-height:calc(100vh - 260px)}.mzk-title{font-size:18px}.mzk-btn{padding:9px 12px}.mzk-controls{padding:8px}}
</style>
<div class="mzk-page"><div class="mzk-app"><div class="mzk-topbar"><div class="mzk-title-block"><div class="mzk-kicker">Maze</div><h1 class="mzk-title"><?php echo htmlspecialchars($viewerTitle, ENT_QUOTES, 'UTF-8'); ?></h1></div><div class="mzk-scorebar"><span class="mzk-score-label">Progress</span><div class="mzk-track"><div class="mzk-fill" id="mzkFill" style="width:0%"></div></div><div class="mzk-badge" id="mzkBadge">0 / <?php echo count($activity['path_sequence']); ?></div></div></div><div class="mzk-stage" id="mzkStage" data-az-zoom><div class="mzk-play-area"><div class="mzk-maze-wrap" id="mzkMazeWrap"></div><div class="mzk-side-rail" id="mzkSideRail"><div class="mzk-controls" id="mzkControls"><button class="mzk-btn secondary" type="button" onclick="mzkRestart()">Restart</button><button class="mzk-btn" type="button" onclick="mzkShowAnswers()">Show Answers</button><button class="mzk-btn next" type="button" onclick="mzkGoNext()" id="mzkNextBtn">Next</button></div><div class="mzk-side-hint">Use the sidebar arrows or swipe. Avoid wall animals and dead ends.</div></div></div><div id="mzkFeedback" aria-live="polite"></div><div class="mzk-completed-screen" id="mzkCompleted"></div></div></div></div>
<audio id="mzkTtsAudio" preload="none"></audio><audio id="mzkWinAudio" src="../../hangman/assets/win.mp3" preload="auto"></audio><audio id="mzkLoseAudio" src="../../hangman/assets/lose.mp3" preload="auto"></audio><audio id="mzkWrongAudio" src="../../hangman/assets/wrong.wav" preload="auto"></audio><audio id="mzkDoneAudio" src="../../hangman/assets/WINNING%20CLAPS.mp3" preload="auto"></audio>
<script src="maze_layout.js"></script><script>
const MZK_TITLE=<?php echo json_encode($viewerTitle, JSON_UNESCAPED_UNICODE); ?>,MZK_ACTIVITY_ID=<?php echo json_encode($activityId, JSON_UNESCAPED_UNICODE); ?>,MZK_RETURN_TO=<?php echo json_encode($returnTo, JSON_UNESCAPED_UNICODE); ?>,MZK_BANK_BY_ID=<?php echo json_encode($bankById, JSON_UNESCAPED_UNICODE); ?>,MZK_PATH=<?php echo json_encode($activity['path_sequence'], JSON_UNESCAPED_UNICODE); ?>,MZK_BRANCHES=<?php echo json_encode($activity['distractor_branches'], JSON_UNESCAPED_UNICODE); ?>,MZK_LAYOUT_POSITIONS=<?php echo json_encode((object)$activity['layout_positions'], JSON_UNESCAPED_UNICODE); ?>,MZK_AUDIO_URLS=<?php echo json_encode($activity['audio_urls'], JSON_UNESCAPED_UNICODE); ?>,MZK_THEME=<?php echo json_encode($activity['theme'], JSON_UNESCAPED_UNICODE); ?>,MZK_TTS_URL='tts.php';
let mzkNextIndex=0,mzkDone=false,mzkScores=[],mzkLastLayout=null,mzkRounds=0;
function mzkPlay(el){try{if(!el)return;el.pause();el.currentTime=0;el.play();}catch(e){}}
function mzkNodeVocab(node){return MZK_BANK_BY_ID[node.vocabularyId]||{image_url:'',word:''};}
function mzkSetFeedback(text,cls){const el=document.getElementById('mzkFeedback');el.textContent=text;el.className=cls||'';}
function mzkUpdateProgress(value){if(typeof value==='number')mzkNextIndex=value;const total=Math.max(1,MZK_PATH.length),pct=Math.round(mzkNextIndex/total*100);document.getElementById('mzkFill').style.width=Math.max(pct,0)+'%';document.getElementById('mzkBadge').textContent=mzkNextIndex+' / '+MZK_PATH.length;}
function mzkSyncArrowProgress(value){mzkNextIndex=Math.max(0,Math.min(MZK_PATH.length,value||0));mzkScores=Array(mzkNextIndex).fill(1);mzkUpdateProgress();}
function mzkClearAnswerPath(){const svg=document.querySelector('#mzkMazeWrap svg');if(!svg)return;svg.querySelectorAll('.mzk-answer-path,.mzk-answer-dot').forEach(el=>el.remove());}
function mzkRenderMazeBaseSafe(NS,svg,layout){mzkRenderMazeBase(NS,svg,layout,{wallColor:'var(--wall)',floorColor:'#ffffff',dotColor:'rgba(83,74,183,.10)'});}
function mzkBuildMaze(){const layout=generateMazeLayout(MZK_PATH,MZK_BRANCHES,MZK_LAYOUT_POSITIONS);mzkLastLayout=layout;const NS='http://www.w3.org/2000/svg';const svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 '+layout.width+' '+layout.height);svg.setAttribute('width',layout.width);svg.setAttribute('height',layout.height);svg.setAttribute('preserveAspectRatio','xMidYMid meet');mzkRenderMazeBaseSafe(NS,svg,layout);const R=Math.round(layout.cellSize*0.39);(layout.fillerCells||[]).forEach((cell,i)=>{const g=mzkRenderFillerIcon(NS,MZK_THEME,i,layout.cellSize);g.setAttribute('transform','translate('+cell.x+','+cell.y+') scale(1.08)');svg.appendChild(g);});layout.nodes.forEach(node=>{const isEndpoint=node.kind==='start'||node.kind==='home';const vocab=isEndpoint?{image_url:'',word:''}:mzkNodeVocab(node);const g=document.createElementNS(NS,'g');g.setAttribute('class','mzk-node'+(node.kind==='branch'?' branch':'')+(node.kind==='start'?' start':'')+(node.kind==='home'?' end':''));g.dataset.nodeId=node.id;g.setAttribute('transform','translate('+node.x+','+node.y+')');const nodeR=node.kind==='home'?Math.round(R*1.5):R;const circle=document.createElementNS(NS,'circle');circle.setAttribute('class','mzk-node-circle');circle.setAttribute('r',nodeR);g.appendChild(circle);if(isEndpoint){const eIcon=mzkRenderEndpointIcon(NS,node.kind);eIcon.setAttribute('transform','scale('+(node.kind==='home'?1.52:1.2)+')');g.appendChild(eIcon);}else if(vocab.image_url){const inset=4;const img=document.createElementNS(NS,'image');img.setAttributeNS('http://www.w3.org/1999/xlink','href',vocab.image_url);img.setAttribute('href',vocab.image_url);img.setAttribute('x',-nodeR+inset);img.setAttribute('y',-nodeR+inset);img.setAttribute('width',(nodeR-inset)*2);img.setAttribute('height',(nodeR-inset)*2);img.setAttribute('clip-path','circle('+(nodeR-inset)+'px)');img.setAttribute('preserveAspectRatio','xMidYMid slice');g.appendChild(img);}if(!isEndpoint)g.addEventListener('click',()=>{if(typeof window.mzkNodeTap==='function'&&window.mzkNodeTap(node))return;mzkHandleTap(node,g);});svg.appendChild(g);});const wrap=document.getElementById('mzkMazeWrap');wrap.innerHTML='';wrap.appendChild(svg);}
function mzkHandleTap(node,groupEl){if(mzkDone)return;if(node.kind==='path'&&node.index===mzkNextIndex){groupEl.classList.add('done');mzkPlay(document.getElementById('mzkWinAudio'));mzkSetFeedback('Great job!','good');mzkSpeakWord(node.vocabularyId);mzkScores.push(1);mzkNextIndex++;mzkUpdateProgress();if(mzkNextIndex>=MZK_PATH.length)setTimeout(mzkFinish,500);return;}groupEl.classList.add('wrong');mzkPlay(document.getElementById(node.kind==='branch'?'mzkWrongAudio':'mzkLoseAudio'));mzkSetFeedback(node.kind==='branch'?'Dead end! Restart and try another path.':'Not yet. Follow the path.','bad');groupEl.classList.add('shake');}
function mzkSpeakWord(vocabularyId){const vocab=MZK_BANK_BY_ID[vocabularyId]||{},word=(vocab.word||'').toLowerCase();if(!word)return;if(window.speechSynthesis){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.rate=0.8;u.pitch=1.05;u.lang='en-US';window.speechSynthesis.speak(u);}}
function mzkFinish(){if(mzkDone)return;mzkDone=true;mzkRounds++;mzkNextIndex=MZK_PATH.length;mzkScores=Array(MZK_PATH.length).fill(1);mzkUpdateProgress();mzkPlay(document.getElementById('mzkDoneAudio'));mzkSetFeedback('Completed!','good');mzkShowUnscoredCompleted();}
function mzkShowUnscoredCompleted(){const stage=document.getElementById('mzkStage');const completedEl=document.getElementById('mzkCompleted');const n=MZK_PATH.length;stage.classList.add('is-completed');completedEl.classList.add('active');completedEl.innerHTML='<div class="af-unscored__card"><p class="af-unscored__prog-label">Path Completed</p><div class="af-unscored__prog-track"><div class="af-unscored__prog-fill" id="mzk-prog-fill" style="width:0%"></div></div><div class="af-unscored__prog-nums"><span>0</span><strong id="mzk-prog-text">0 / 0</strong></div><div class="af-unscored__icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#7F77DD" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg></div><p class="af-unscored__title">Maze complete!</p><p class="af-unscored__sub">Great job! You found the way home.</p><div class="af-unscored__chips af-unscored__chips--2"><div class="af-unscored__chip"><div class="af-unscored__chip-val af-unscored__chip-val--orange" id="mzk-stat1">0</div><div class="af-unscored__chip-lbl">Steps Completed</div></div><div class="af-unscored__chip"><div class="af-unscored__chip-val" id="mzk-stat2">0</div><div class="af-unscored__chip-lbl">Rounds</div></div></div><div class="af-unscored__banner af-unscored__banner--orange"><div class="af-unscored__banner-icon af-unscored__banner-icon--orange"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg></div><div class="af-unscored__banner-text af-unscored__banner-text--orange"><span class="af-unscored__banner-title">Keep up the great work!</span>Try the maze again or continue to the next activity.</div></div><div class="af-unscored__btns"><button class="af-unscored__btn-secondary" id="mzkRestartCompleted">↺ Play Again</button><button class="af-unscored__btn-primary" id="mzkNextCompleted">Next →</button></div></div>';document.getElementById('mzk-prog-fill').style.width='100%';document.getElementById('mzk-prog-text').textContent=n+' / '+n;document.getElementById('mzk-stat1').textContent=String(n);document.getElementById('mzk-stat2').textContent=String(mzkRounds);document.getElementById('mzkRestartCompleted').addEventListener('click',mzkRestart);document.getElementById('mzkNextCompleted').addEventListener('click',mzkGoNext);if(MZK_RETURN_TO&&MZK_ACTIVITY_ID){const sep=MZK_RETURN_TO.indexOf('?')!==-1?'&':'?';fetch(MZK_RETURN_TO+sep+'activity_percent=100&activity_errors=0&activity_total='+n+'&activity_id='+encodeURIComponent(MZK_ACTIVITY_ID)+'&activity_type=maze_kids',{method:'GET',credentials:'same-origin',cache:'no-store'}).catch(function(){});}}
function mzkResetViewerState(){mzkNextIndex=0;mzkDone=false;mzkScores=[];document.getElementById('mzkStage').classList.remove('is-completed');document.getElementById('mzkCompleted').classList.remove('active');document.getElementById('mzkCompleted').innerHTML='';mzkSetFeedback('','');mzkUpdateProgress();}
function mzkRestart(){mzkResetViewerState();mzkBuildMaze();}
function mzkShowAnswers(){const svg=document.querySelector('#mzkMazeWrap svg');if(!svg)return;mzkClearAnswerPath();const layout=mzkLastLayout||generateMazeLayout(MZK_PATH,MZK_BRANCHES,MZK_LAYOUT_POSITIONS);const ordered=[];const start=layout.nodes.find(n=>n.kind==='start');const home=layout.nodes.find(n=>n.kind==='home');if(start)ordered.push(start);layout.nodes.filter(n=>n.kind==='path').sort((a,b)=>a.index-b.index).forEach(n=>ordered.push(n));if(home)ordered.push(home);if(ordered.length<2)return;const NS='http://www.w3.org/2000/svg';const d=ordered.map((n,i)=>(i?'L ':'M ')+n.x+' '+n.y).join(' ');const path=document.createElementNS(NS,'path');path.setAttribute('class','mzk-answer-path');path.setAttribute('d',d);svg.appendChild(path);ordered.forEach(n=>{const dot=document.createElementNS(NS,'circle');dot.setAttribute('class','mzk-answer-dot');dot.setAttribute('cx',n.x);dot.setAttribute('cy',n.y);dot.setAttribute('r',n.kind==='start'||n.kind==='home'?12:8);svg.appendChild(dot);});mzkSetFeedback('Answer path shown. Follow the orange line from START to HOME.','good');}
function mzkGoNext(){const candidates=Array.from(document.querySelectorAll('a,button')).filter(el=>!['mzkNextBtn','mzkNextCompleted'].includes(el.id));const target=candidates.find(el=>/next|finish unit|continue/i.test((el.textContent||'').trim())&&el.offsetParent!==null);if(target){target.click();return;}if(MZK_RETURN_TO){window.location.href=MZK_RETURN_TO;return;}window.history.back();}
mzkBuildMaze();mzkUpdateProgress();
</script><?php
$content = ob_get_clean();
render_activity_viewer($viewerTitle, 'Maze', $content);
