<?php
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../core/_activity_viewer_template.php';

$activityId = isset($_GET['id']) ? trim((string) $_GET['id']) : '';
$unit = isset($_GET['unit']) ? trim((string) $_GET['unit']) : '';
$returnTo = isset($_GET['return_to']) ? trim((string) $_GET['return_to']) : '';

if ($activityId === '' && $unit === '') die('Activity not specified');

function lc_resolve_unit(PDO $pdo, string $id): string {
    if ($id === '') return '';
    $stmt = $pdo->prepare('SELECT unit_id FROM activities WHERE id=:id LIMIT 1');
    $stmt->execute(['id' => $id]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    return $row ? (string)($row['unit_id'] ?? '') : '';
}
function lc_normalize(mixed $raw): array {
    $default = ['title' => "Let's Classify", 'instructions' => '', 'cefr' => 'A1', 'label_mode' => 'both', 'categories' => [], 'items' => []];
    if ($raw === null || $raw === '') return $default;
    $decoded = is_string($raw) ? json_decode($raw, true) : $raw;
    return is_array($decoded) ? array_merge($default, $decoded) : $default;
}
function lc_load(PDO $pdo, string $activityId, string $unit): array {
    $fallback = array_merge(lc_normalize(null), ['id' => '']);
    $row = null;
    if ($activityId !== '') {
        $stmt = $pdo->prepare("SELECT id,data FROM activities WHERE id=:id AND type='lets_classify' LIMIT 1");
        $stmt->execute(['id' => $activityId]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
    }
    if (!$row && $unit !== '') {
        $stmt = $pdo->prepare("SELECT id,data FROM activities WHERE unit_id=:unit AND type='lets_classify' ORDER BY id ASC LIMIT 1");
        $stmt->execute(['unit' => $unit]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
    }
    if (!$row) return $fallback;
    $payload = lc_normalize($row['data'] ?? null);
    $payload['id'] = (string)($row['id'] ?? '');
    return $payload;
}

if ($unit === '' && $activityId !== '') $unit = lc_resolve_unit($pdo, $activityId);
$activity = lc_load($pdo, $activityId, $unit);
if ($activityId === '' && !empty($activity['id'])) $activityId = (string)$activity['id'];

$viewerTitle = (string)($activity['title'] ?? "Let's Classify");
$instructions = (string)($activity['instructions'] ?? '');
$labelMode = (string)($activity['label_mode'] ?? 'both');
$categories = is_array($activity['categories']) ? array_values($activity['categories']) : [];
$items = is_array($activity['items']) ? array_values($activity['items']) : [];

if (count($categories) < 2) die('No categories found for this activity');
if (count($items) < 2) die('No items found for this activity');
shuffle($items);

$catsJson = json_encode($categories, JSON_UNESCAPED_UNICODE);
$itemsJson = json_encode($items, JSON_UNESCAPED_UNICODE);

ob_start();
?>
<link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@500;600;700&family=Nunito:wght@600;700;800;900&display=swap" rel="stylesheet">
<style>
:root{--lc-orange:#F97316;--lc-purple:#7F77DD;--lc-purple-dark:#534AB7;--lc-purple-soft:#EEEDFE;--lc-purple-line:#C9C3F4;--lc-muted:#9B94BE;--lc-green:#16a34a;--lc-red:#ef4444;--lc-ink:#1E1B3A}
html,body{width:100%;min-height:100%;overflow:visible!important}body{margin:0!important;padding:0!important;background:#fff!important;font-family:'Nunito','Segoe UI',sans-serif!important}.activity-wrapper{max-width:100%!important;margin:0!important;padding:0!important;height:auto!important;min-height:100%!important;display:block!important;background:transparent!important}.top-row,.activity-header,.activity-title,.activity-subtitle{display:none!important}.viewer-content{display:block!important;min-height:auto!important;height:auto!important;overflow:visible!important;padding:0!important;margin:0!important;background:transparent!important;border:none!important;box-shadow:none!important;border-radius:0!important}
.lc-page{width:100%;min-height:auto;overflow:visible!important;padding:clamp(8px,1.2vw,16px);box-sizing:border-box;background:#fff;display:block}.lc-app{width:min(1180px,100%);margin:0 auto;display:block;min-height:auto}.lc-topbar{height:24px;display:flex;align-items:center;justify-content:center;margin-bottom:0}.lc-topbar-title{font-size:11px;font-weight:900;color:var(--lc-muted);letter-spacing:.1em;text-transform:uppercase}.lc-hero{text-align:center;margin-bottom:8px}.lc-kicker{display:inline-flex;align-items:center;justify-content:center;padding:6px 13px;border-radius:999px;background:#FFF0E6;border:1px solid #FCDDBF;color:#C2580A;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;margin-bottom:7px}.lc-hero h1{font-family:'Fredoka',sans-serif;font-size:clamp(30px,3.9vw,46px);font-weight:700;color:var(--lc-orange);margin:0;line-height:1.02}.lc-hero p{font-size:clamp(13px,1.35vw,16px);font-weight:800;color:var(--lc-muted);margin:6px 0 0}.lc-stage{background:#fff;border:1px solid #F0EEF8;border-radius:22px;padding:12px 14px 12px;box-shadow:0 8px 36px rgba(127,119,221,.11);box-sizing:border-box;overflow:visible!important;display:block;height:auto!important;min-height:0!important}
.lc-layout{display:grid;grid-template-columns:minmax(330px,390px) minmax(0,820px);grid-template-areas:"pool cats";gap:14px;align-items:start;justify-content:center;overflow:visible!important;height:auto!important;min-height:0!important}.lc-col-pool{grid-area:pool;min-width:0;display:flex;flex-direction:column;gap:9px;overflow:visible!important;background:#FAFAFE;border:2px dashed #E5E1FA;border-radius:18px;padding:12px;box-sizing:border-box}.lc-col-pool.drag-over{border-color:var(--lc-purple);background:#F7F5FF;box-shadow:0 0 0 4px rgba(127,119,221,.10)}.lc-col-cats{grid-area:cats;min-width:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;align-content:start;overflow:visible!important;padding:1px}
.lc-cat-card{position:relative;border-radius:18px;overflow:visible!important;min-height:clamp(150px,16vw,180px)!important;height:auto!important;background:var(--lc-purple-soft)!important;border:2px solid var(--lc-purple-line)!important;box-shadow:0 5px 18px rgba(127,119,221,.13)!important;transition:box-shadow .15s,outline-color .1s,transform .12s;display:flex;flex-direction:column}.lc-cat-card.drag-over{box-shadow:0 8px 26px rgba(127,119,221,.28)!important;outline:3px solid var(--lc-purple);outline-offset:2px;transform:translateY(-1px)}.lc-cat-bg-img,.lc-cat-gradient{display:none!important}.lc-cat-name-badge{position:relative;z-index:3;margin:8px auto 5px;max-width:calc(100% - 18px);padding:7px 14px;border-radius:999px;background:#fff;color:var(--lc-purple-dark);font-family:'Fredoka',sans-serif;font-size:clamp(15px,1.6vw,20px);font-weight:700;text-align:center;box-shadow:0 4px 12px rgba(127,119,221,.16);pointer-events:none}.lc-cat-chips-area{position:relative;z-index:4;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-items:start;gap:8px;margin:5px 8px 8px;padding:8px;min-height:95px;height:auto!important;flex:0 0 auto;border:2px dashed var(--lc-purple-line);border-radius:14px;background:rgba(255,255,255,.42);box-sizing:border-box;pointer-events:none;overflow:visible!important}.lc-cat-chips-area::before{content:'Drop answers here';position:absolute;inset:0;display:flex;align-items:center;justify-content:center;text-align:center;font-size:12px;font-weight:900;letter-spacing:.04em;color:var(--lc-muted);pointer-events:none}.lc-cat-chips-area:has(.lc-chip-sticker)::before{display:none}
.lc-chip-sticker{position:relative;pointer-events:auto;display:flex;align-items:center;justify-content:center;gap:6px;border-radius:12px;overflow:hidden;border:2px solid #fff;box-shadow:0 4px 12px rgba(0,0,0,.16);cursor:grab;background:#fff;transition:box-shadow .12s,border-color .12s,transform .12s;box-sizing:border-box;touch-action:none;max-width:100%;width:100%!important;min-width:0}.lc-chip-sticker:hover{box-shadow:0 7px 18px rgba(127,119,221,.22);transform:translateY(-1px)}.lc-chip-sticker.dragging{opacity:.45;transform:scale(.94)}.lc-chip-sticker.has-image{aspect-ratio:1/1;height:auto!important;flex:0 0 auto}.lc-chip-sticker.text-only{min-height:42px;padding:9px 8px;flex:0 0 auto}.lc-chip-sticker img{width:100%;height:100%;object-fit:contain;display:block;pointer-events:none;background:#fff}.lc-chip-sticker .lc-chip-lbl{font-size:clamp(12px,1.05vw,15px);font-weight:900;text-align:center;line-height:1.15;pointer-events:none;color:var(--lc-ink);white-space:normal;overflow-wrap:break-word;hyphens:auto}.lc-chip-sticker.has-image .lc-chip-lbl{position:absolute;bottom:0;left:0;right:0;background:rgba(30,27,58,.76);color:#fff;font-size:10px;padding:4px 5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.lc-chip-sticker.is-correct{border-color:var(--lc-green);cursor:default}.lc-chip-sticker.is-wrong{border-color:var(--lc-red)}.lc-chip-sticker .lc-result-icon{position:absolute;top:4px;right:5px;font-size:14px;line-height:1;display:none;filter:drop-shadow(0 1px 2px rgba(0,0,0,.28))}.lc-chip-sticker.is-correct .lc-result-icon,.lc-chip-sticker.is-wrong .lc-result-icon{display:block}
.lc-pool-label{font-size:12px;font-weight:900;color:var(--lc-muted);letter-spacing:.08em;text-transform:uppercase;text-align:center}.lc-pool{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));grid-auto-flow:row;gap:10px;align-content:start;overflow:visible!important;padding:2px;min-height:0;flex:0 0 auto}.lc-pool.drag-over{background:#F9F9FF;border-radius:16px;box-shadow:inset 0 0 0 2px var(--lc-purple)}.lc-pool-empty-hint{color:var(--lc-muted);font-size:13px;font-weight:800;padding:18px 8px;text-align:center;grid-column:1/-1}.lc-pool-chip{display:flex;align-items:center;justify-content:center;gap:6px;padding:9px 8px;background:#fff;border:2px solid #EDE9FA;border-bottom-width:4px;border-radius:13px;cursor:grab;user-select:none;min-width:0;box-shadow:0 3px 10px rgba(127,119,221,.13);transition:transform .12s,box-shadow .12s,border-color .12s;box-sizing:border-box;touch-action:none}.lc-pool-chip:hover{transform:translateY(-2px);box-shadow:0 6px 18px rgba(127,119,221,.20);border-color:var(--lc-purple)}.lc-pool-chip.dragging{opacity:.4;transform:scale(.95)}.lc-pool-chip.has-image{aspect-ratio:1/1;flex-direction:column;min-height:0}.lc-pool-chip.text-only{grid-column:auto;min-height:42px}.lc-pool-chip img{width:100%;height:100%;min-height:0;object-fit:contain;border-radius:8px;pointer-events:none;background:#fff}.lc-pool-chip .lc-pool-chip-lbl{font-size:clamp(12px,1.05vw,15px);font-weight:900;color:var(--lc-ink);pointer-events:none;line-height:1.15;text-align:center;max-width:100%;white-space:normal;overflow-wrap:break-word;hyphens:auto;flex-shrink:0}.lc-pool-chip.has-image .lc-pool-chip-lbl{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.lc-score-grid{display:none;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px}.lc-score-grid.visible{display:grid}.lc-score-card{background:#FAFAFE;border:1px solid #EDE9FA;border-radius:14px;padding:12px;text-align:center}.lc-score-num{font-family:'Fredoka',sans-serif;font-weight:700;font-size:26px;line-height:1}.lc-score-num.c{color:var(--lc-green)}.lc-score-num.w{color:var(--lc-red)}.lc-score-num.p{color:var(--lc-purple)}.lc-score-lbl{margin-top:5px;font-size:10px;font-weight:900;color:var(--lc-muted);text-transform:uppercase;letter-spacing:.08em}.lc-controls{border-top:1px solid #F0EEF8;margin-top:12px;padding-top:12px;text-align:center;display:flex;align-items:center;justify-content:center;gap:10px;flex-wrap:wrap;flex-shrink:0;clear:both}.lc-btn{display:inline-flex;align-items:center;justify-content:center;padding:13px 26px;border:none;border-radius:8px;color:#fff;cursor:pointer;font-weight:900;font-size:13px;line-height:1;box-shadow:0 6px 18px rgba(127,119,221,.18);transition:transform .12s,filter .12s}.lc-btn:hover{filter:brightness(1.07);transform:translateY(-1px)}.lc-btn-check{background:var(--lc-orange);box-shadow:0 6px 18px rgba(249,115,22,.22)}.lc-btn:disabled{opacity:.5;pointer-events:none}.lc-completed{display:none;text-align:center;padding:28px 12px;max-width:520px;margin:0 auto}.lc-completed.active{display:block}.lc-completed-icon{font-size:34px;line-height:1;margin-bottom:8px}.lc-completed-title{margin:0 0 6px;color:var(--lc-orange);font-family:'Fredoka',sans-serif;font-size:34px;font-weight:700}.lc-completed-text{color:var(--lc-muted);font-size:14px;font-weight:800;line-height:1.5;margin:0}.lc-completed-score{font-size:15px;font-weight:900;color:var(--lc-purple-dark);margin:6px 0 14px}.lc-completed-actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap}.lc-completed-btn{display:inline-flex;align-items:center;justify-content:center;padding:11px 22px;border:none;border-radius:8px;cursor:pointer;min-width:120px;font-weight:700;font-size:14px;line-height:1;box-shadow:0 6px 18px rgba(127,119,221,.18)}.lc-completed-btn.restart{background:var(--lc-purple);color:#fff}.lc-completed-btn.back{background:#F0EEF8;color:var(--lc-purple-dark)}#lc-ghost{position:fixed;pointer-events:none;z-index:9999;display:none;min-width:90px;max-width:240px;min-height:70px;border-radius:14px;box-shadow:0 8px 28px rgba(127,119,221,.3);opacity:.92;overflow:hidden;background:#fff;border:2px solid #fff}#lc-ghost img{width:100%;height:100%;object-fit:contain;background:#fff}
@media(max-width:900px){.lc-layout{grid-template-columns:1fr;grid-template-areas:"pool" "cats";overflow:visible;justify-content:stretch}.lc-col-pool{min-height:auto;overflow:visible}.lc-pool{grid-template-columns:repeat(3,minmax(0,1fr));overflow:visible}.lc-col-cats{overflow:visible;grid-template-columns:repeat(2,minmax(0,1fr))}.lc-cat-chips-area{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:660px){.lc-pool{grid-template-columns:repeat(3,minmax(0,1fr))}.lc-col-cats{grid-template-columns:1fr}.lc-cat-card{min-height:180px!important}.lc-cat-chips-area{grid-template-columns:repeat(3,minmax(0,1fr))}.lc-controls{flex-direction:column;gap:8px}.lc-btn{width:100%}.lc-score-grid{grid-template-columns:1fr}}
</style>
<div class="lc-page" id="lc-page"><div class="lc-app" id="lc-app"><div class="lc-topbar"><span class="lc-topbar-title">Let's Classify</span></div><div class="lc-hero"><div class="lc-kicker">Activity</div><h1><?php echo htmlspecialchars($viewerTitle, ENT_QUOTES, 'UTF-8'); ?></h1><?php if ($instructions !== ''): ?><p><?php echo htmlspecialchars($instructions, ENT_QUOTES, 'UTF-8'); ?></p><?php endif; ?></div><div class="lc-stage" id="lc-stage"><div class="lc-layout" id="lc-layout"><div class="lc-col-pool" id="lc-col-pool"><div class="lc-pool-label">Sort these items</div><div class="lc-pool" id="lc-pool"></div></div><div class="lc-col-cats" id="lc-col-cats"><?php foreach ($categories as $cat): $catId=(int)($cat['id']??0); $catName=htmlspecialchars((string)($cat['name']??''),ENT_QUOTES,'UTF-8'); ?><div class="lc-cat-card" id="lc-cat-<?php echo $catId; ?>" data-cat="<?php echo $catId; ?>"><?php if ($catName !== ''): ?><div class="lc-cat-name-badge"><?php echo $catName; ?></div><?php endif; ?><div class="lc-cat-chips-area" id="lc-chips-<?php echo $catId; ?>"></div></div><?php endforeach; ?></div></div><div id="lc-score-grid" class="lc-score-grid"><div class="lc-score-card"><div class="lc-score-num c" id="lc-s-correct">0</div><div class="lc-score-lbl">Correct</div></div><div class="lc-score-card"><div class="lc-score-num w" id="lc-s-wrong">0</div><div class="lc-score-lbl">Wrong</div></div><div class="lc-score-card"><div class="lc-score-num p" id="lc-s-pct">0%</div><div class="lc-score-lbl">Score</div></div></div><div class="lc-controls" id="lc-controls"><button type="button" class="lc-btn lc-btn-check" id="lc-check-btn">Check</button></div><div class="lc-completed" id="lc-completed"><div class="lc-completed-icon">OK</div><h2 class="lc-completed-title" id="lc-completed-title">Completed!</h2><div id="lc-completed-score-grid" class="lc-score-grid" style="max-width:360px;margin:0 auto 12px"><div class="lc-score-card"><div class="lc-score-num c" id="lc-cs-correct">0</div><div class="lc-score-lbl">Correct</div></div><div class="lc-score-card"><div class="lc-score-num w" id="lc-cs-wrong">0</div><div class="lc-score-lbl">Wrong</div></div><div class="lc-score-card"><div class="lc-score-num p" id="lc-cs-pct">0%</div><div class="lc-score-lbl">Score</div></div></div><p class="lc-completed-text" id="lc-completed-text"></p><p class="lc-completed-score" id="lc-completed-score-line"></p><div class="lc-completed-actions"><button type="button" class="lc-completed-btn restart" id="lc-restart-btn">Restart</button><?php if ($returnTo !== ''): ?><button type="button" class="lc-completed-btn back" id="lc-back-btn">Back</button><?php endif; ?></div></div></div></div></div><div id="lc-ghost"></div><audio id="lc-win-sound" src="../../hangman/assets/win.mp3" preload="auto"></audio><audio id="lc-done-sound" src="../../hangman/assets/win (1).mp3" preload="auto"></audio><audio id="lc-item-audio" preload="none"></audio>
<script>
(function(){'use strict';
const LC_CATS=<?= $catsJson ?>,LC_ITEMS_SRC=<?= $itemsJson ?>,LC_LABEL_MODE=<?= json_encode($labelMode, JSON_UNESCAPED_UNICODE) ?>,LC_TITLE=<?= json_encode($viewerTitle, JSON_UNESCAPED_UNICODE) ?>,LC_RETURN_TO=<?= json_encode($returnTo, JSON_UNESCAPED_UNICODE) ?>,LC_ACT_ID=<?= json_encode($activityId, JSON_UNESCAPED_UNICODE) ?>;
let placement={},checked=false,correct=0,wrong=0,dragItemId=null,touchItemId=null,touchItemEl=null;
const poolEl=document.getElementById('lc-pool'),poolColEl=document.getElementById('lc-col-pool'),scoreGridEl=document.getElementById('lc-score-grid'),sCorrectEl=document.getElementById('lc-s-correct'),sWrongEl=document.getElementById('lc-s-wrong'),sPctEl=document.getElementById('lc-s-pct'),checkBtn=document.getElementById('lc-check-btn'),completedEl=document.getElementById('lc-completed'),compTitleEl=document.getElementById('lc-completed-title'),compTextEl=document.getElementById('lc-completed-text'),compScoreEl=document.getElementById('lc-completed-score-line'),csgridEl=document.getElementById('lc-completed-score-grid'),csCorrectEl=document.getElementById('lc-cs-correct'),csWrongEl=document.getElementById('lc-cs-wrong'),csPctEl=document.getElementById('lc-cs-pct'),controlsEl=document.getElementById('lc-controls'),restartBtn=document.getElementById('lc-restart-btn'),backBtn=document.getElementById('lc-back-btn'),ghostEl=document.getElementById('lc-ghost'),winSound=document.getElementById('lc-win-sound'),doneSound=document.getElementById('lc-done-sound'),itemAudio=document.getElementById('lc-item-audio');
function escHtml(str){return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function resizeHost(){requestAnimationFrame(()=>{const page=document.getElementById('lc-page'),app=document.getElementById('lc-app');const h=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,page?page.scrollHeight:0,app?app.scrollHeight:0)+24;try{if(window.frameElement){window.frameElement.style.height=h+'px';window.frameElement.style.minHeight=h+'px';}}catch(e){}try{window.parent.postMessage({type:'activity-resize',activity:'lets_classify',height:h},'*')}catch(e){}})}
function initPlacement(){placement={};LC_ITEMS_SRC.forEach(item=>{placement[item.id]=null})}
function hasVisibleImage(item){return Boolean(item.image&&LC_LABEL_MODE!=='name')}
function chipTypeClass(item){return hasVisibleImage(item)?'has-image':'text-only'}
function buildPoolChip(item){const el=document.createElement('div');el.className='lc-pool-chip '+chipTypeClass(item);el.dataset.itemId=item.id;el.dataset.catId=item.category_id;el.draggable=true;let inner='';if(hasVisibleImage(item))inner+=`<img src="${escHtml(item.image)}" alt="${escHtml(item.name)}" loading="lazy">`;if(LC_LABEL_MODE!=='image'||!item.image)inner+=`<span class="lc-pool-chip-lbl">${escHtml(item.name)}</span>`;el.innerHTML=inner;el.addEventListener('dragstart',onDragStart);el.addEventListener('dragend',onDragEnd);el.addEventListener('touchstart',onTouchStart,{passive:false});if(item.audio)el.addEventListener('click',()=>{if(!dragItemId)playItemAudio(item.audio)});return el}
function buildStickerChip(item,pos){const el=document.createElement('div');el.className='lc-chip-sticker '+chipTypeClass(item);el.dataset.itemId=item.id;el.dataset.catId=item.category_id;let inner='';if(hasVisibleImage(item))inner+=`<img src="${escHtml(item.image)}" alt="${escHtml(item.name)}" loading="lazy">`;if(LC_LABEL_MODE==='name'||LC_LABEL_MODE==='both')inner+=`<span class="lc-chip-lbl">${escHtml(item.name)}</span>`;inner+='<span class="lc-result-icon" aria-hidden="true"></span>';el.innerHTML=inner;if(!checked){el.draggable=true;el.addEventListener('dragstart',onDragStart);el.addEventListener('dragend',onDragEnd);el.addEventListener('touchstart',onTouchStart,{passive:false})}else{const ok=pos.catId===item.category_id;el.classList.toggle('is-correct',ok);el.classList.toggle('is-wrong',!ok);const icon=el.querySelector('.lc-result-icon');if(icon)icon.textContent=ok?'OK':'X'}return el}
function render(){poolEl.innerHTML='';const poolItems=LC_ITEMS_SRC.filter(i=>placement[i.id]===null);if(poolItems.length===0)poolEl.innerHTML='<span class="lc-pool-empty-hint">All items placed<br><small>Drag any answer back here to change it.</small></span>';else poolItems.forEach(item=>poolEl.appendChild(buildPoolChip(item)));LC_CATS.forEach(cat=>{const area=document.getElementById('lc-chips-'+cat.id);if(!area)return;area.innerHTML='';LC_ITEMS_SRC.filter(i=>{const p=placement[i.id];return p!==null&&p.catId===cat.id}).forEach(item=>area.appendChild(buildStickerChip(item,placement[item.id])))});setupDropZones();resizeHost()}
function createPlacement(catEl){return{catId:parseInt(catEl.dataset.cat,10)}}
function setupDropZones(){LC_CATS.forEach(cat=>{const catEl=document.getElementById('lc-cat-'+cat.id);if(!catEl)return;catEl.ondragover=e=>{e.preventDefault();catEl.classList.add('drag-over')};catEl.ondragleave=e=>{if(!catEl.contains(e.relatedTarget))catEl.classList.remove('drag-over')};catEl.ondrop=e=>{e.preventDefault();catEl.classList.remove('drag-over');if(checked)return;const itemId=parseInt(e.dataTransfer.getData('text/plain'),10);if(isNaN(itemId))return;placement[itemId]=createPlacement(catEl);render()}});[poolEl,poolColEl].forEach(zone=>{if(!zone)return;zone.ondragover=e=>{e.preventDefault();poolEl.classList.add('drag-over');poolColEl.classList.add('drag-over')};zone.ondragleave=e=>{if(!zone.contains(e.relatedTarget)){poolEl.classList.remove('drag-over');poolColEl.classList.remove('drag-over')}};zone.ondrop=e=>{e.preventDefault();poolEl.classList.remove('drag-over');poolColEl.classList.remove('drag-over');const itemId=parseInt(e.dataTransfer.getData('text/plain'),10);if(!isNaN(itemId)&&!checked){placement[itemId]=null;render()}}})}
function onDragStart(e){if(checked){e.preventDefault();return}dragItemId=parseInt(e.currentTarget.dataset.itemId,10);e.dataTransfer.setData('text/plain',dragItemId);e.dataTransfer.effectAllowed='move';setTimeout(()=>e.currentTarget.classList.add('dragging'),0)}
function onDragEnd(e){e.currentTarget.classList.remove('dragging');dragItemId=null;resizeHost()}
function onTouchStart(e){if(checked||e.touches.length!==1)return;e.preventDefault();const el=e.currentTarget;touchItemId=parseInt(el.dataset.itemId,10);touchItemEl=el;ghostEl.innerHTML=el.innerHTML;ghostEl.style.width=el.offsetWidth+'px';ghostEl.style.height=el.offsetHeight+'px';ghostEl.style.display='block';moveGhost(e.touches[0]);el.classList.add('dragging');document.addEventListener('touchmove',onTouchMove,{passive:false});document.addEventListener('touchend',onTouchEnd,{passive:false})}
function moveGhost(t){const w=ghostEl.offsetWidth||84,h=ghostEl.offsetHeight||84;ghostEl.style.left=(t.clientX-w/2)+'px';ghostEl.style.top=(t.clientY-h/2)+'px'}
function onTouchMove(e){if(!touchItemEl)return;e.preventDefault();moveGhost(e.touches[0]);clearDragOver();const zone=zoneFromPoint(e.touches[0].clientX,e.touches[0].clientY);if(zone)zone.classList.add('drag-over')}
function onTouchEnd(e){document.removeEventListener('touchmove',onTouchMove);document.removeEventListener('touchend',onTouchEnd);ghostEl.style.display='none';ghostEl.innerHTML='';clearDragOver();if(!touchItemEl)return;touchItemEl.classList.remove('dragging');const t=e.changedTouches[0],catEl=catZoneFromPoint(t.clientX,t.clientY);if(catEl&&!checked)placement[touchItemId]=createPlacement(catEl);else if(poolFromPoint(t.clientX,t.clientY)&&!checked)placement[touchItemId]=null;touchItemEl=null;touchItemId=null;render()}
function clearDragOver(){document.querySelectorAll('.lc-cat-card.drag-over,.lc-pool.drag-over,.lc-col-pool.drag-over').forEach(el=>el.classList.remove('drag-over'))}
function zoneFromPoint(x,y){return catZoneFromPoint(x,y)||(poolFromPoint(x,y)?poolColEl:null)}
function catZoneFromPoint(x,y){return[...document.querySelectorAll('.lc-cat-card')].find(z=>{const r=z.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom})||null}
function poolFromPoint(x,y){const r=poolColEl.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
function playItemAudio(url){itemAudio.src=url;itemAudio.currentTime=0;itemAudio.play().catch(()=>{})}
function playSound(el){try{el.currentTime=0;el.play()}catch(e){}}
function checkAnswers(){const placed=LC_ITEMS_SRC.filter(i=>placement[i.id]!==null);if(placed.length<LC_ITEMS_SRC.length){alert('Place all items before checking!');return}checked=true;correct=LC_ITEMS_SRC.filter(i=>{const p=placement[i.id];return p!==null&&p.catId===i.category_id}).length;wrong=LC_ITEMS_SRC.length-correct;const pct=LC_ITEMS_SRC.length>0?Math.round(correct/LC_ITEMS_SRC.length*100):0;sCorrectEl.textContent=correct;sWrongEl.textContent=wrong;sPctEl.textContent=pct+'%';scoreGridEl.classList.add('visible');render();checkBtn.disabled=true;const nextBtn=document.createElement('button');nextBtn.type='button';nextBtn.className='lc-btn lc-btn-check';nextBtn.textContent='Finish';nextBtn.addEventListener('click',showCompleted);controlsEl.appendChild(nextBtn);if(wrong===0)playSound(winSound);resizeHost()}
async function showCompleted(){const pct=LC_ITEMS_SRC.length>0?Math.round(correct/LC_ITEMS_SRC.length*100):0;document.getElementById('lc-layout').style.display='none';scoreGridEl.style.display='none';controlsEl.style.display='none';if(compTitleEl)compTitleEl.textContent=LC_TITLE||"Let's Classify";if(compTextEl)compTextEl.textContent="You've completed this activity. Great job!";if(compScoreEl)compScoreEl.textContent=correct+' correct · '+wrong+' wrong · '+pct+'%';if(csCorrectEl)csCorrectEl.textContent=correct;if(csWrongEl)csWrongEl.textContent=wrong;if(csPctEl)csPctEl.textContent=pct+'%';if(csgridEl)csgridEl.style.display='grid';completedEl.classList.add('active');playSound(doneSound);resizeHost();if(LC_ACT_ID&&LC_RETURN_TO){const sep=LC_RETURN_TO.includes('?')?'&':'?',url=LC_RETURN_TO+sep+'activity_percent='+pct+'&activity_errors='+wrong+'&activity_total='+LC_ITEMS_SRC.length+'&activity_id='+encodeURIComponent(LC_ACT_ID)+'&activity_type=lets_classify';try{const r=await fetch(url,{method:'GET',credentials:'same-origin',cache:'no-store'});if(!r.ok)window.location.href=url}catch(e){window.location.href=url}}}
function restartActivity(){checked=false;correct=0;wrong=0;initPlacement();document.getElementById('lc-layout').style.display='';scoreGridEl.classList.remove('visible');scoreGridEl.style.display='';controlsEl.style.display='';completedEl.classList.remove('active');checkBtn.disabled=false;controlsEl.querySelectorAll('button:not(#lc-check-btn)').forEach(b=>b.remove());render()}
checkBtn.addEventListener('click',checkAnswers);if(restartBtn)restartBtn.addEventListener('click',restartActivity);if(backBtn)backBtn.addEventListener('click',()=>{try{if(window.top&&window.top!==window.self){window.top.location.href=LC_RETURN_TO;return}}catch(e){}window.location.href=LC_RETURN_TO});window.addEventListener('resize',resizeHost);if('ResizeObserver'in window){new ResizeObserver(resizeHost).observe(document.getElementById('lc-app'))}initPlacement();render();setTimeout(resizeHost,150);setTimeout(resizeHost,600);
})();
</script>
<?php
$content = ob_get_clean();
render_activity_viewer($viewerTitle, 'Classify', $content);
